\documentclass{mwart}
%\usepackage{polski}
%\usepackage[polish]{babel}
\usepackage{amsfonts}
\usepackage{indentfirst}
\usepackage[utf8]{inputenc}
\usepackage{amsthm}
\usepackage{multirow}
\usepackage{amsmath}
\newtheorem{tw}{Twierdzenie}
\newtheorem{df}{Definicja}
\newtheorem{zd}{Zadanie}
\newtheorem{zdt}[zd]{Zadanie*}
\title{Kolokwium 2\\Grupa A}
\begin{document}
\SweaveOpts{concordance=TRUE}
\maketitle


\end{document}
