SELECT * FROM ETATY;
DESCRIBE ETATY;

INSERT INTO ETATY VALUES ('STAZYSTA', 100, 500);
INSERT INTO ETATY VALUE ('SPRZEDAWCA', 500, 1000);

INSERT INTO ETATY VALUE ('STAZYSTA', 100, 500), ('SPRZEDAWCA', 500, 1000);

INSERT INTO ETATY (NAZWA) VALUE ('STAZYSTA');
INSERT INTO ETATY (NAZWA, PLACA_OD) VALUE ('SPRZEDAWCA', 500);
INSERT INTO ETATY (NAZWA, PLACA_OD, PLACA_DO) VALUE ('DYREKTOR', 500, 1000);

INSERT INTO ETATY SET NAZWA='MECHANIK', PLACA_DO=750;
INSERT INTO ETATY SET PLACA_DO=900;

# WTRACENIA
SELECT * FROM ETATY;
INSERT IGNORE INTO ETATY VALUES ('STAZYSTA', 500, 500);
INSERT INTO ETATY VALUES ('STAZYSTA', 500, 1000);
INSERT INTO ETATY VALUES ('STAZYSTA', 500, 1000) ON DUPLICATE KEY UPDATE NAZWA='STAZYSTA';
INSERT DELAYED INTO ETATY VALUE ('KIEROWCA', 400, 1000);

#############################################################
DELETE FROM ETATY;

DELETE FROM ETATY WHERE NAZWA='STAZYSTA';

DELETE FROM ETATY WHERE PLACA_OD > 100 ORDER BY PLACA_OD, NAZWA LIMIT 2;
SELECT * FROM ETATY ORDER BY PLACA_OD;

DELETE FROM ETATY WHERE PLACA_OD > 100 ORDER BY PLACA_OD, NAZWA LIMIT 2 RETURNING NAZWA, PLACA_OD, PLACA_DO;

################################################################
SELECT * FROM ETATY;
UPDATE ETATY SET PLACA_OD = 5000;
UPDATE ETATY SET PLACA_OD = 1000 WHERE NAZWA='DOKTORANT';
UPDATE ETATY SET PLACA_OD = 1000 WHERE PLACA_OD = 5000 ORDER BY NAZWA LIMIT 2;
UPDATE ETATY SET NAZWA='PROGRAMISTA' WHERE NAZWA='INFORMATYK';
UPDATE ETATY SET NAZWA='ASYSTENT' WHERE NAZWA='PROGRAMISTA';

UPDATE ETATY SET PLACA_OD=100, PLACA_DO=1000 WHERE NAZWA='DOKTORANT';



