SELECT AGENT_NAME, COMMISSION
    FROM SALESMAN;

SELECT ORD_DATE, AGENT_CODE, ORD_NUM, ORD_AMOUNT
    FROM ORDERS;

SELECT DISTINCT AGENT_CODE
    FROM ORDERS;

SELECT AGENT_NAME, WORKING_AREA
    FROM SALESMAN
    WHERE WORKING_AREA LIKE 'PARIS';

SELECT *
    FROM CUSTOMER
    WHERE GRADE = 2;

SELECT ORD_NUM, ORD_DATE, ORD_AMOUNT
    FROM ORDERS
    WHERE AGENT_CODE = 'A004';

SELECT CUST_NAME
    FROM CUSTOMER
    WHERE GRADE > 1;

SELECT CUST_NAME
    FROM CUSTOMER
    WHERE CUST_CITY LIKE 'NEW YORK' AND GRADE > 1;

SELECT CUST_NAME
    FROM CUSTOMER
    WHERE CUST_CITY LIKE 'NEW YORK' OR GRADE > 1;

SELECT CUST_NAME
    FROM CUSTOMER
    WHERE CUST_CITY LIKE 'NEW YORK' AND GRADE <= 1;

SELECT *
    FROM ORDERS
    WHERE (CAST(SUBSTRING(AGENT_CODE FROM 2) AS INT) <= 12 AND ORD_DATE != "2012-09-10") OR ORD_AMOUNT <= 1000;

SELECT AGENT_CODE, AGENT_NAME, WORKING_AREA, COMMISSION
    FROM SALESMAN
    WHERE COMMISSION > 0.1 AND COMMISSION < 0.12;

SELECT ORD_NUM
    FROM ORDERS
    WHERE ORD_AMOUNT < 200
      AND NOT (ORD_DATE > "2008-02-10" AND (CAST(SUBSTRING(CUST_CODE FROM 2) AS INT) < 15));

SELECT *
    FROM ORDERS
    WHERE NOT ((ORD_DATE = "2008-08-17" AND ORD_AMOUNT < 1000)
                   OR (CAST(SUBSTRING(CUST_CODE FROM 2) AS INT) > 17
                           AND ORD_AMOUNT < 1000));

SELECT *
    FROM SALESMAN
    WHERE WORKING_AREA LIKE 'TORENTO' OR WORKING_AREA LIKE 'BRISBAN';

SELECT *
    FROM SALESMAN
    WHERE WORKING_AREA NOT LIKE 'TORENTO' AND WORKING_AREA NOT LIKE 'BRISBAN';

SELECT AGENT_CODE, AGENT_NAME, WORKING_AREA, COMMISSION
    FROM SALESMAN
    WHERE WORKING_AREA NOT LIKE 'LONDON' AND WORKING_AREA NOT LIKE 'NEW YORK';

SELECT *
    FROM CUSTOMER
    WHERE CAST(SUBSTRING(CUST_CODE FROM 2) AS INT) IN (17, 18, 19);

SELECT *
    FROM SALESMAN
    WHERE COMMISSION BETWEEN 0.12 AND 0.14;

SELECT *
    FROM ORDERS
    WHERE ORD_AMOUNT BETWEEN 500 AND 4000
      AND ORD_AMOUNT != 948.5
      AND ORD_AMOUNT != 1983.43;

SELECT *
    FROM SALESMAN
    WHERE AGENT_NAME LIKE 'A%' OR AGENT_NAME LIKE 'K%';

SELECT SUM(ORD_AMOUNT)
    FROM ORDERS;

SELECT AVG(ORD_AMOUNT)
    FROM ORDERS;

SELECT COUNT(DISTINCT AGENT_CODE)
    FROM ORDERS;

SELECT COUNT(*)
    FROM CUSTOMER;

SELECT COUNT(GRADE)
    FROM CUSTOMER;

SELECT MAX(ORD_AMOUNT)
    FROM ORDERS;

SELECT MIN(ORD_AMOUNT)
    FROM ORDERS;

SELECT CUST_CITY, MAX(GRADE)
    FROM CUSTOMER
    GROUP BY CUST_CITY;

SELECT CUST_CODE, MAX(ORD_AMOUNT)
    FROM ORDERS
    GROUP BY CUST_CODE;

SELECT CUST_CODE, ORD_DATE, MAX(ORD_AMOUNT)
    FROM ORDERS
    GROUP BY CUST_CODE, ORD_DATE;

SELECT ORD_DATE, AGENT_CODE, MAX(ORD_AMOUNT)
    FROM ORDERS
    WHERE ORD_DATE = "2008-07-20"
    GROUP BY AGENT_CODE, ORD_DATE;

SELECT ORD_DATE, CUST_CODE, MAX(ORD_AMOUNT)
    FROM ORDERS
    GROUP BY ORD_DATE, CUST_CODE
    HAVING MAX(ORD_AMOUNT) > 2000;

SELECT ORD_NUM, ORD_DATE, MAX(ORD_AMOUNT)
    FROM ORDERS
    GROUP BY ORD_DATE, CUST_CODE
    HAVING MAX(ORD_AMOUNT) BETWEEN 2000 AND 6000;

SELECT ORD_NUM, ORD_DATE, MAX(ORD_AMOUNT)
    FROM ORDERS
    GROUP BY ORD_DATE, CUST_CODE
    HAVING MAX(ORD_AMOUNT) IN (2000, 3000, 5760, 6000);

SELECT CUST_CODE, MAX(ORD_AMOUNT)
    FROM ORDERS
    WHERE CAST(SUBSTRING(CUST_CODE FROM 2) AS INT) BETWEEN 10 AND 17
    GROUP BY CUST_CODE;

SELECT CUST_CODE, ORD_AMOUNT
    FROM ORDERS
    WHERE CAST(SUBSTRING(CUST_CODE FROM 2) AS INT) BETWEEN 10 AND 17
    GROUP BY CUST_CODE
    HAVING MAX(ORD_AMOUNT) > 1000;

SELECT AGENT_CODE, MAX(ORD_AMOUNT)
    FROM ORDERS
    WHERE CAST(SUBSTRING(AGENT_CODE FROM 2) AS INT) BETWEEN 8 AND 10
    GROUP BY AGENT_CODE;

SELECT COUNT(*)
    FROM ORDERS
    WHERE ORD_DATE = '2008-08-15';

SELECT COUNT(DISTINCT AGENT_CODE)
    FROM SALESMAN
    WHERE WORKING_AREA IS NOT NULL;

SELECT ORD_DATE, AGENT_CODE, COUNT(*)
    FROM ORDERS
    GROUP BY ORD_DATE, AGENT_CODE;

SELECT CONCAT(CAST(COMMISSION*100 AS INT), '%') AS COMMISSION,
       AGENT_CODE,
       AGENT_NAME,
       WORKING_AREA
    FROM SALESMAN;

SELECT CONCAT_WS(' ', 'For', ORD_DATE, 'there are', COUNT(*), 'orders')
    FROM ORDERS
    GROUP BY ORD_DATE;

SELECT ORD_NUM
    FROM ORDERS
    ORDER BY ORD_NUM;

SELECT ORD_NUM,ORD_DATE
    FROM ORDERS
    ORDER BY ORD_DATE DESC;

SELECT *
    FROM ORDERS
    ORDER BY ORD_DATE, ORD_AMOUNT DESC;

SELECT *
    FROM CUSTOMER
    ORDER BY CUST_CODE;

SELECT AGENT_CODE, ORD_DATE, ORD_AMOUNT
    FROM ORDERS
    ORDER BY AGENT_CODE, ORD_DATE;

SELECT CUST_NAME, WORKING_AREA, GRADE
    FROM CUSTOMER
    ORDER BY GRADE DESC;

SELECT CUST_CODE, COUNT(DISTINCT ORD_NUM) AS NO_ORDERS, MAX(ORD_AMOUNT)
    FROM ORDERS
    GROUP BY CUST_CODE
    ORDER BY NO_ORDERS DESC;

SELECT ORD_DATE, SUM(ORD_AMOUNT) AS TOTAL, SUM(ORD_AMOUNT)*0.15 AS COMM
    FROM ORDERS
    GROUP BY ORD_DATE
    ORDER BY ORD_DATE;

SELECT SALESMAN.AGENT_NAME AS SALESMAN, CUSTOMER.CUST_NAME, CUSTOMER.WORKING_AREA
    FROM SALESMAN
    INNER JOIN CUSTOMER
        ON SALESMAN.WORKING_AREA = CUSTOMER.WORKING_AREA;

SELECT O.ORD_NUM, O.ORD_AMOUNT, C.CUST_NAME, C.WORKING_AREA
    FROM ORDERS O
    INNER JOIN CUSTOMER C on O.CUST_CODE = C.CUST_CODE
    WHERE O.ORD_AMOUNT BETWEEN 500 AND 2000;

SELECT C.CUST_NAME, S.AGENT_NAME
    FROM CUSTOMER C
    INNER JOIN SALESMAN S on C.AGENT_CODE = S.AGENT_CODE;

SELECT C.CUST_NAME AS CUSTOMER_NAME, C.WORKING_AREA, S.AGENT_NAME AS SALESMAN, S.COMMISSION
    FROM CUSTOMER C
    INNER JOIN SALESMAN S on C.AGENT_CODE = S.AGENT_CODE
    WHERE S.COMMISSION > 0.12;

SELECT O.ORD_NUM, O.ORD_AMOUNT, O.ORD_DATE, C.CUST_NAME, S.AGENT_NAME
    FROM ORDERS O
    LEFT JOIN CUSTOMER C on O.CUST_CODE = C.CUST_CODE
    LEFT JOIN SALESMAN S on C.AGENT_CODE = S.AGENT_CODE;

#59

SELECT C.CUST_NAME, C.WORKING_AREA, C.GRADE, S.AGENT_NAME
    FROM CUSTOMER C
    LEFT JOIN SALESMAN S on C.AGENT_CODE = S.AGENT_CODE
    ORDER BY C.CUST_CODE;

SELECT C.CUST_NAME, C.WORKING_AREA, C.GRADE, S.AGENT_NAME
    FROM CUSTOMER C
    LEFT JOIN SALESMAN S on C.AGENT_CODE = S.AGENT_CODE
    WHERE C.GRADE < 2
    ORDER BY C.CUST_CODE;

#FULL JOIN
SELECT C.CUST_NAME, C.WORKING_AREA, O.ORD_NUM, O.ORD_DATE, O.ORD_AMOUNT
    FROM CUSTOMER C
    LEFT JOIN ORDERS O on C.CUST_CODE = O.CUST_CODE
UNION
    SELECT C.CUST_NAME, C.WORKING_AREA, O.ORD_NUM, O.ORD_DATE, O.ORD_AMOUNT
        FROM CUSTOMER C
        RIGHT JOIN ORDERS O on C.CUST_CODE = O.CUST_CODE
ORDER BY ORD_DATE;

SELECT C.CUST_NAME, C.WORKING_AREA, O.ORD_NUM, O.ORD_DATE, O.ORD_AMOUNT, S.AGENT_NAME, S.COMMISSION
    FROM CUSTOMER C
    LEFT JOIN SALESMAN S on C.AGENT_CODE = S.AGENT_CODE
    LEFT JOIN ORDERS O on C.CUST_CODE = O.CUST_CODE;

SELECT C.CUST_NAME, C.WORKING_AREA, C.GRADE, S.AGENT_NAME, S.WORKING_AREA
    FROM CUSTOMER C
    RIGHT JOIN SALESMAN S on C.AGENT_CODE = S.AGENT_CODE
    ORDER BY S.AGENT_CODE;

SELECT C.CUST_NAME, C.WORKING_AREA, C.GRADE, S.AGENT_NAME,
        O.ORD_NUM, O.ORD_DATE, O.ORD_AMOUNT
    FROM CUSTOMER C
    RIGHT JOIN SALESMAN S on C.AGENT_CODE = S.AGENT_CODE
    RIGHT JOIN ORDERS O on C.CUST_CODE = O.CUST_CODE;

SELECT C.CUST_NAME, C.WORKING_AREA, C.GRADE, S.AGENT_NAME,
       O.ORD_NUM, O.ORD_DATE, O.ORD_AMOUNT
    FROM CUSTOMER C
    RIGHT JOIN SALESMAN S on C.AGENT_CODE = S.AGENT_CODE
    LEFT JOIN ORDERS O on C.CUST_CODE = O.CUST_CODE
    WHERE O.ORD_AMOUNT >= 2000 AND C.GRADE IS NOT NULL;

SELECT *
    FROM CUSTOMER C
    CROSS JOIN SALESMAN S;

SELECT *
    FROM CUSTOMER C
    CROSS JOIN SALESMAN S
    WHERE S.WORKING_AREA IS NOT NULL;

SELECT *
    FROM CUSTOMER C
    CROSS JOIN SALESMAN S
    WHERE S.WORKING_AREA IS NOT NULL AND C.GRADE IS NOT NULL;

SELECT *
    FROM CUSTOMER C
    CROSS JOIN SALESMAN S
    WHERE S.WORKING_AREA != C.WORKING_AREA AND C.GRADE IS NOT NULL;

SELECT S.AGENT_NAME AS NAME
    FROM SALESMAN S
    WHERE S.WORKING_AREA LIKE 'LONDON'
UNION ALL
    SELECT C.CUST_NAME
        FROM CUSTOMER C
        WHERE C.WORKING_AREA LIKE 'LONDON';

SELECT DISTINCT AGENT_CODE, AGENT_NAME, WORKING_AREA
    FROM SALESMAN;

SELECT S.AGENT_NAME AS NAME
    FROM SALESMAN S
UNION ALL
    SELECT C.CUST_NAME
        FROM CUSTOMER C;

SELECT CUST_CODE, WORKING_AREA, GRADE, IF(GRADE >= 3, 'High rating', 'Low rating') AS RATING
    FROM CUSTOMER;






