SELECT AGENT_NAME, COMMISSION
    FROM SALESMAN;

SELECT ORD_DATE, AGENT_CODE, ORD_NUM, ORD_AMOUNT
    FROM ORDERS;

SELECT DISTINCT AGENT_CODE
    FROM ORDERS;

SELECT AGENT_NAME, WORKING_AREA
    FROM SALESMAN
    WHERE WORKING_AREA LIKE 'PARIS';

SELECT *
    FROM CUSTOMER
    WHERE GRADE = 2;

SELECT ORD_NUM, ORD_DATE, ORD_AMOUNT
    FROM ORDERS
    WHERE AGENT_CODE = 'A004';

SELECT CUST_NAME
    FROM CUSTOMER
    WHERE GRADE > 1;

SELECT CUST_NAME
    FROM CUSTOMER
    WHERE CUST_CITY LIKE 'NEW YORK' AND GRADE > 1;

SELECT CUST_NAME
    FROM CUSTOMER
    WHERE CUST_CITY LIKE 'NEW YORK' OR GRADE > 1;

SELECT CUST_NAME
    FROM CUSTOMER
    WHERE CUST_CITY LIKE 'NEW YORK' AND GRADE <= 1;

SELECT *
    FROM ORDERS
    WHERE (CAST(SUBSTRING(AGENT_CODE FROM 2) AS INT) <= 12 AND ORD_DATE != "2012-09-10") OR ORD_AMOUNT <= 1000;

SELECT AGENT_CODE, AGENT_NAME, WORKING_AREA, COMMISSION
    FROM SALESMAN
    WHERE COMMISSION > 0.1 AND COMMISSION < 0.12;

SELECT ORD_NUM
    FROM ORDERS
    WHERE ORD_AMOUNT < 200
      AND NOT (ORD_DATE > "2012-02-10" AND (CAST(SUBSTRING(CUST_CODE FROM 2) AS INT) < 15));

SELECT *
    FROM ORDERS
    WHERE NOT ((ORD_DATE = "2012-08-17" AND ORD_AMOUNT < 1000)
                   OR (CAST(SUBSTRING(CUST_CODE FROM 2) AS INT) > 17
                           AND ORD_AMOUNT < 1000));

SELECT *
    FROM SALESMAN
    WHERE WORKING_AREA LIKE 'TORENTO' OR WORKING_AREA LIKE 'BRISBAN';

SELECT *
    FROM SALESMAN
    WHERE WORKING_AREA NOT LIKE 'TORENTO' AND WORKING_AREA NOT LIKE 'BRISBAN';

SELECT AGENT_CODE, AGENT_NAME, WORKING_AREA, COMMISSION
    FROM SALESMAN
    WHERE WORKING_AREA NOT LIKE 'LONDON' AND WORKING_AREA NOT LIKE 'NEW YORK';

SELECT *
    FROM CUSTOMER
    WHERE CAST(SUBSTRING(CUST_CODE FROM 2) AS INT) IN (17, 18, 19);

SELECT *
    FROM SALESMAN
    WHERE COMMISSION BETWEEN 0.12 AND 0.14;

SELECT *
    FROM ORDERS
    WHERE ORD_AMOUNT BETWEEN 500 AND 4000
      AND ORD_AMOUNT != 948.5
      AND ORD_AMOUNT != 1983.43;

SELECT *
    FROM SALESMAN
    WHERE AGENT_NAME LIKE 'A%' OR AGENT_NAME LIKE 'K%';

SELECT SUM(ORD_AMOUNT)
    FROM ORDERS;

SELECT AVG(ORD_AMOUNT)
    FROM ORDERS;

SELECT COUNT(DISTINCT AGENT_CODE)
    FROM ORDERS;

SELECT COUNT(*)
    FROM CUSTOMER;

SELECT COUNT(GRADE)
    FROM CUSTOMER;

SELECT MAX(ORD_AMOUNT)
    FROM ORDERS;

SELECT MIN(ORD_AMOUNT)
    FROM ORDERS;

SELECT CUST_CITY, MAX(GRADE)
    FROM CUSTOMER
    GROUP BY CUST_CITY;

SELECT CUST_CODE, MAX(ORD_AMOUNT)
    FROM ORDERS
    GROUP BY CUST_CODE;

SELECT CUST_CODE, ORD_DATE, MAX(ORD_AMOUNT)
    FROM ORDERS
    GROUP BY CUST_CODE, ORD_DATE;

SELECT ORD_DATE, AGENT_CODE, MAX(ORD_AMOUNT)
    FROM ORDERS
    WHERE ORD_DATE = "2008-07-20"
    GROUP BY AGENT_CODE, ORD_DATE;

SELECT ORD_NUM, CUST_CODE, MAX(ORD_AMOUNT)
    FROM ORDERS
    GROUP BY ORD_NUM, CUST_CODE
    HAVING MAX(ORD_AMOUNT) > 2000;

SELECT ORD_NUM, ORD_DATE, MAX(ORD_AMOUNT)
    FROM ORDERS
    GROUP BY ORD_DATE, CUST_CODE
    HAVING MAX(ORD_AMOUNT) BETWEEN 2000 AND 6000;

SELECT ORD_NUM, ORD_DATE, MAX(ORD_AMOUNT)
    FROM ORDERS
    GROUP BY ORD_DATE, CUST_CODE
    HAVING MAX(ORD_AMOUNT) IN (2000, 3000, 5760, 6000);

SELECT CUST_CODE, MAX(ORD_AMOUNT)
    FROM ORDERS
    WHERE CAST(SUBSTRING(CUST_CODE FROM 2) AS INT) BETWEEN 10 AND 17
    GROUP BY CUST_CODE;

SELECT CUST_CODE, ORD_AMOUNT
    FROM ORDERS
    WHERE CAST(SUBSTRING(CUST_CODE FROM 2) AS INT) BETWEEN 10 AND 17
    GROUP BY CUST_CODE
    HAVING MAX(ORD_AMOUNT) > 1000;

# 39

