---
title: "Procesy stochastyczne - intro"
# author: "Grzegorz Mika"
# date: "2020-09-10"
output: pdf_document
---

## Kwestie organizacyjne

1. Materiały, prezentacje, skrypty itp. dostępne będą we wspólnym folderze na Google Drivie. Liczę, że nie będzie problemów w postaci różnych "sprytnych" zagrań jak usuwanie plików - cała historia zapisuje się na Google Drivie! Zestawy zadań umieszczane będą również na [stronie](https://grzegorzmika.github.io/Academia/).

2. Dostęp do dysku jest pod tym [linkiem](https://bit.ly/32yOHX8) (wymagane jest konto Google, w razie gdy ktoś nie ma, można założyć za darmo).

3. Zajęcia będą odbywać się z wykorzystaniem platformy MS Teams. Zaproszenia na zajęcia wysłane są dla kanałów stworzonych osobno dla grupy 1 i 2.

4. Do kanałów dla poszczególnych grup proszę dołączać zgodnie z tym, w zajęciach której grupy będzie się uczestniczyć - domyślnie powinna być to grupa przypisana w USOS, w razie potrzeby zmiany grupy, proszę o informację.

5. Organizacja zajęć może ulec zmianie wraz ze zdobywaniem doświadczenia i nowymi wytycznymi dotyczączącymi prowadzenia zajęć.

## Wymagania

1. Zalicznie przedmiotu odbywać się będzie na bazie dwóch kolowkiów i aktywności.

2. Przewidziane są dwa kolokwia po 50 punktów.

3. Aktywność doliczana jest do całkowitej sumy punktów.

4. W celu zaliczenia wymagane jest zdobycie co najmnje 51% możliwych do zdobycia punktów, czyli 51 pkt.


